[project]
name = "quarto-repl-mode"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "ipython>=9.10.0",
    "panflute>=2.3",
    "quarto>=0.1.0",
]

[dependency-groups]
dev = [
    "pytest>=8.0",
    "ruff>=0.15.1",
]
